name: Build Windows Executable

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install pyinstaller PyQt6 pygame pillow

    - name: Generate Icons
      run: |
        pip install pillow
        python scripts/generate_icons.py windows

    - name: Build Executable
      run: |
        pyinstaller --onefile --windowed --name RainSound --icon assets/icons/app.ico --add-data "assets;assets" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RainSound-Windows
        path: dist/RainSound.exe
